const Conversation = require('../schema/conversations');
const { errorLogger } = require('./logErrors');

const conversationLimitMiddleware = async (req, res, next) => {
	try {
		// count the number of conversations that this user has had already. If > 5 return error.
		// userType is bot because we want to get messages that have been generated by openai for this user.
		const userConversations = await Conversation.find({
			userId: req.user.id,
			userType: 'bot',
		});

		if (!userConversations) {
			return res.status(500).json({
				error: true,
				message: 'Something went wrong.',
				data: null,
			});
		}

		if (userConversations.length >= 20) {
			return res.status(400).json({
				error: true,
				message: 'conversation_limit_reached',
				data: null,
			});
		}

		next();
	} catch (err) {
		errorLogger(err);

		return res.status(500).json({
			error: true,
			message: 'Something went wrong.',
			data: null,
		});
	}
};

module.exports = {
	conversationLimitMiddleware,
};
